---
title: "introduction"
author: "Youn Kyeong Chang (uni# yc3242)"
date: "November 19, 2018"
output: html_document
---

Due to its large population, New York City requires a powerful, quick, well-equipped and effective Emergency Medical Service System.

BMJ. 2001 Jun 9; 322(7299): 1385–1388.
Effect of reducing ambulance response times on deaths from out of hospital cardiac arrest: cohort study

Currently, the ambulance service has a statutory obligation to arrive at the scene of 50% of emergency calls within 7 minutes and 90% within 14 minutes. The government is considering reducing this target to 90% within 8 minutes.3 Another way to reduce delays would be for other first responders, such as firefighters, the police, or community volunteers, to be supplied with “intelligent” defibrillators within a medically controlled system.4 The fire service, for example, has more stations than the ambulance service to allow it to meet its more stringent targets—90% of vehicles are required to attend the scene of a fire within 5 minutes of the emergency call.

EMERGENCY MEDICAL SERVICES RESPONSE TIME AND MORTALITY IN AN URBAN SETTING
PREHOSPITAL EMERGENCY CARE 2012;16:142–151
Modern emergency medical services (EMS) is the
first level of health care response for out-of-hospital
medical emergencies. Historically, one of the first
interventions that prehospital personnel performed
was rapid response to a scene and rapid return of
a patient to hospital by use of lights and siren.


Neighborhood Poverty and 9-1-1 Ambulance Response Time.

Seim J, Glenn MJ, English J, Sporer K., 2018 Jan 30

PMID: 29381111 DOI: 10.1080/10903127.2017.1416209

This study done in California county early this year challenges the commonly held assumption that ambulances are later to poor neighborhoods. This got us interested in exploring the relationship in emergency response time between a economically well off area - Upper West Side and a relatively poorer area such as Washington Heigths. 
